version: "3"
services:
  realworld_db:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: realworld

  realworld_db_testing:
    image: postgres:latest
    ports:
      - "5433:5432"
    expose:
      - 5433
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: realworld_testing
      POSTGRES_PORT: 5433

 