# fly.toml app configuration file generated for simplefeed on 2023-09-24T19:07:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "simplefeed"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "8080"
  DATABASE_ENVIRONMENT = "production"
  AWS_REGION="eu-central-1"
  S3_ENABLED="true"
  S3_ENDPOINT="https://s3.tebi.io"
  S3_BUCKET_NAME="simplefeed"
  ELASTICSEARCH_ENABLED="false"
  ELASTICSEARCH_NODE="http://elastic.example.com"
